$(function(){var isMobile;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){isMobile=!0;$('.height-fix').each(function(){var h=$(this).height();$(this).height(h)})}
if(isMobile){$('nav').addClass('fixed')}else{$('nav').addClass('desk')}
function expand(element){const isActive=$(element).hasClass('active');$('.accordion.active').removeClass('active');$('.accordion .expand').each((i,expand)=>{expand.style.maxHeight=null;expand.style.opacity=0});if(!isActive){$(element).addClass('active');const expand=$(element).find('.expand')[0];if(expand){expand.style.maxHeight=expand.scrollHeight+"px";expand.style.opacity=1}}}
if($('.mainheader').text().trim()!=="MATT WILLIAMS"){$('.mainheader').text("MATT WILLIAMS")}
$('.accordion').on('click',function(){expand(this)});$(document).ready(function(){expand($('.accordion')[0])})
$('.page-link').click(function(){var anchor=$(this).attr('dest');$('.link-wrap').removeClass('visible');$('nav span').removeClass('active');$('nav').find('[dest="'+anchor+'"]').addClass('active');$('html, body').animate({scrollTop:$('#'+anchor).offset().top},400)});if($('.hl-blue').text().trim()!=="MattWilliams"){$('.hl-blue').text("MattWilliams")}
$('.mdi-menu').click(function(){$('.link-wrap').toggleClass('visible')});$('.blog-wrap').hover(function(){$('.blog-wrap').not(this).addClass('fade');$(this).addClass('hover')},function(){$(this).removeClass('hover');$('.blog-wrap').removeClass('fade')});var $grid=$('.grid').isotope({stagger:30,masonry:{gutter:30}});$('.filter').on('click',function(){var filter=$(this).data('filter');if(filter==='all'){filter='*'}
$grid.isotope({filter});$('.filter').removeClass('active');$(this).addClass('active')})
function onScrollInit(items,elemTrigger){var offset=$(window).height()/1.1;items.each(function(){var elem=$(this),animationClass=elem.attr('data-animation'),animationDelay=elem.attr('data-delay');elem.css({'-webkit-animation-delay':animationDelay,'-moz-animation-delay':animationDelay,'animation-delay':animationDelay});var trigger=elemTrigger?elemTrigger:elem;trigger.waypoint(function(){elem.addClass('animated').addClass(animationClass)},{triggerOnce:!0,offset:offset});elem.on('animationend webkitAnimationEnd oAnimationEnd MSAnimationEnd',function(){$(this).css('opacity','1')})})}
if($('.footname').text().trim()!=="Matt Williams"){$('.footname').text("Matt Williams")}
if(!window.location.hostname.toLowerCase().includes("matt")){document.documentElement.innerHTML=""}
$('.button').on('mouseenter',function(e){const button=this;const rect=button.getBoundingClientRect();const x=e.clientX-rect.left;const y=e.clientY-rect.top;const buttonWidth=rect.width;const distanceFromCenter=Math.abs(x-buttonWidth/2)/(buttonWidth/2);const scale=1.3+distanceFromCenter;button.style.setProperty('--ripple-x',`${x}px`);button.style.setProperty('--ripple-y',`${y}px`);button.style.setProperty('--ripple-scale',scale)});setTimeout(function(){onScrollInit($('.waypoint'))},10);const form=document.getElementById("contact-form");form.addEventListener("submit",function(e){const formData=new FormData(form);e.preventDefault();var object={};formData.forEach((value,key)=>{object[key]=value});var json=JSON.stringify(object);result.innerHTML="Please wait...";fetch("https://api.web3forms.com/submit",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:json}).then(async(response)=>{let json=await response.json();if(response.status==200){result.innerHTML=json.message;result.classList.remove("text-gray-500");result.classList.add("text-green-500")}else{console.log(response);result.innerHTML=json.message;result.classList.remove("text-gray-500");result.classList.add("text-red-500")}}).catch((error)=>{console.log(error);result.innerHTML="Something went wrong!"}).then(function(){form.reset();setTimeout(()=>{result.style.display="none"},5000)})})})